insert into student (name, birthdate, address, gender) values ('Archibold Dunnett', '1988-07-14', 'Florida', 'Male');
insert into student (name, birthdate, address, gender) values ('Darcie Pelling', '1956-09-09', 'California', 'Female');
insert into student (name, birthdate, address, gender) values ('Ruthy Pighills', '1965-05-15', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Maryellen Caston', '1976-01-02', 'District of Columbia', 'Female');
insert into student (name, birthdate, address, gender) values ('Maryann Biggam', '1949-01-02', 'Rhode Island', 'Female');
insert into student (name, birthdate, address, gender) values ('Christal Thulborn', '1964-09-16', 'Florida', 'Female');
insert into student (name, birthdate, address, gender) values ('Curtice Ayrs', '1994-04-11', 'Arizona', 'Male');
insert into student (name, birthdate, address, gender) values ('Regan Stannard', '1942-07-01', 'Ohio', 'Male');
insert into student (name, birthdate, address, gender) values ('Berta Hessenthaler', '1953-03-16', 'California', 'Female');
insert into student (name, birthdate, address, gender) values ('Maxwell Abramino', '1973-07-15', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Seka Bilbie', '1952-05-18', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Tony Lillie', '1974-10-01', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Bobbi Girdler', '1971-05-31', 'Virginia', 'Female');
insert into student (name, birthdate, address, gender) values ('Lorine Mackerness', '1971-05-15', 'Maryland', 'Female');
insert into student (name, birthdate, address, gender) values ('Gustavo Wibberley', '1932-02-07', 'District of Columbia', 'Male');
insert into student (name, birthdate, address, gender) values ('Rocky Gates', '1954-08-28', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Netti Millthorpe', '1985-07-25', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Britney Sargood', '1987-06-30', 'Oklahoma', 'Female');
insert into student (name, birthdate, address, gender) values ('Gaylene Harman', '2004-06-14', 'New Jersey', 'Female');
insert into student (name, birthdate, address, gender) values ('Silas Caulton', '1979-07-14', 'Georgia', 'Male');
insert into student (name, birthdate, address, gender) values ('Claudette Kehoe', '1987-02-17', 'District of Columbia', 'Female');
insert into student (name, birthdate, address, gender) values ('Boyce Kivits', '1992-09-04', 'Michigan', 'Male');
insert into student (name, birthdate, address, gender) values ('Lion Pinyon', '1939-08-05', 'Maryland', 'Male');
insert into student (name, birthdate, address, gender) values ('Tabor Tunsley', '1963-03-29', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Swen Huckerbe', '1981-11-08', 'Pennsylvania', 'Male');
insert into student (name, birthdate, address, gender) values ('Tedra Verbeek', '1988-01-19', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Reggie Astman', '1989-04-03', 'Kansas', 'Female');
insert into student (name, birthdate, address, gender) values ('Arluene Spratt', '1994-10-11', 'Iowa', 'Female');
insert into student (name, birthdate, address, gender) values ('Dario Fetherby', '1985-01-20', 'Virginia', 'Male');
insert into student (name, birthdate, address, gender) values ('Warren Pannett', '1996-09-07', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Aleda Kiwitz', '1993-05-13', 'Tennessee', 'Female');
insert into student (name, birthdate, address, gender) values ('Mariette Kaindl', '1934-04-27', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Llywellyn Donisthorpe', '2000-08-28', 'California', 'Male');
insert into student (name, birthdate, address, gender) values ('Sheppard Shorey', '2000-03-29', 'Kansas', 'Male');
insert into student (name, birthdate, address, gender) values ('Dian Tighe', '1958-02-16', 'Indiana', 'Female');
insert into student (name, birthdate, address, gender) values ('Olva Eric', '1998-06-12', 'California', 'Female');
insert into student (name, birthdate, address, gender) values ('Butch Hemeret', '1938-12-10', 'Tennessee', 'Male');
insert into student (name, birthdate, address, gender) values ('Cahra Pendrill', '1955-08-04', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Nomi Kimmince', '1999-08-18', 'Maryland', 'Female');
insert into student (name, birthdate, address, gender) values ('Celie Flecknell', '1964-02-13', 'Oklahoma', 'Female');
insert into student (name, birthdate, address, gender) values ('Gordy Moy', '1939-06-30', 'Alabama', 'Male');
insert into student (name, birthdate, address, gender) values ('Ronny Hugk', '1934-08-14', 'Florida', 'Male');
insert into student (name, birthdate, address, gender) values ('Gloria Dufton', '1951-04-21', 'Florida', 'Female');
insert into student (name, birthdate, address, gender) values ('Carlen McLeese', '1956-02-09', 'Virginia', 'Female');
insert into student (name, birthdate, address, gender) values ('Raine Foskin', '1992-01-04', 'North Carolina', 'Female');
insert into student (name, birthdate, address, gender) values ('Wells Axup', '1990-11-11', 'Utah', 'Male');
insert into student (name, birthdate, address, gender) values ('Alejandrina Izkovitch', '1974-10-07', 'Nebraska', 'Female');
insert into student (name, birthdate, address, gender) values ('Torrance Sorrel', '1990-09-01', 'Colorado', 'Male');
insert into student (name, birthdate, address, gender) values ('Kanya Coggings', '1940-07-04', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Maje Hinchon', '1966-04-29', 'New York', 'Male');
insert into student (name, birthdate, address, gender) values ('Clare Muffin', '1961-01-27', 'District of Columbia', 'Male');
insert into student (name, birthdate, address, gender) values ('Abigale Cissell', '1992-09-02', 'Pennsylvania', 'Female');
insert into student (name, birthdate, address, gender) values ('Hagen Blind', '1939-08-07', 'Illinois', 'Male');
insert into student (name, birthdate, address, gender) values ('Adolpho Sessuns', '1941-01-22', 'South Carolina', 'Male');
insert into student (name, birthdate, address, gender) values ('Carmelina MacDonald', '2001-10-19', 'Massachusetts', 'Female');
insert into student (name, birthdate, address, gender) values ('Beth Geroldini', '1957-10-14', 'Illinois', 'Female');
insert into student (name, birthdate, address, gender) values ('Deeanne Bloxham', '1979-09-01', 'New Jersey', 'Female');
insert into student (name, birthdate, address, gender) values ('Saundra Dener', '1945-06-25', 'District of Columbia', 'Male');
insert into student (name, birthdate, address, gender) values ('Ardelia Logan', '1953-09-06', 'Florida', 'Female');
insert into student (name, birthdate, address, gender) values ('Dolly Rizzini', '1976-10-22', 'Connecticut', 'Female');
insert into student (name, birthdate, address, gender) values ('Andonis De Zamudio', '1933-03-18', 'Florida', 'Male');
insert into student (name, birthdate, address, gender) values ('Alameda Bredgeland', '1993-11-08', 'Florida', 'Female');
insert into student (name, birthdate, address, gender) values ('Marchall Matousek', '1935-09-02', 'Kansas', 'Male');
insert into student (name, birthdate, address, gender) values ('Galvan Statersfield', '1980-09-24', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Nanni Testro', '1992-10-09', 'Utah', 'Female');
insert into student (name, birthdate, address, gender) values ('Eadie Bront', '1976-07-31', 'California', 'Female');
insert into student (name, birthdate, address, gender) values ('Zachary Redfield', '1969-07-14', 'Massachusetts', 'Male');
insert into student (name, birthdate, address, gender) values ('Orton Oles', '1968-11-27', 'Colorado', 'Male');
insert into student (name, birthdate, address, gender) values ('Ivan Binestead', '1990-07-12', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Page Kinsell', '1997-03-14', 'Oregon', 'Male');
insert into student (name, birthdate, address, gender) values ('Trista Nordass', '1945-11-01', 'Utah', 'Female');
insert into student (name, birthdate, address, gender) values ('Ardith Cardis', '1940-05-05', 'New York', 'Female');
insert into student (name, birthdate, address, gender) values ('Sadye Durkin', '1950-05-06', 'Pennsylvania', 'Female');
insert into student (name, birthdate, address, gender) values ('Thorsten Attenburrow', '1974-07-17', 'New York', 'Male');
insert into student (name, birthdate, address, gender) values ('Harley Bracco', '1939-05-14', 'Massachusetts', 'Male');
insert into student (name, birthdate, address, gender) values ('Bennett Veare', '1937-11-08', 'Ohio', 'Male');
insert into student (name, birthdate, address, gender) values ('Konrad Suttill', '1993-06-15', 'Kentucky', 'Male');
insert into student (name, birthdate, address, gender) values ('Valene Ratie', '1943-11-16', 'District of Columbia', 'Female');
insert into student (name, birthdate, address, gender) values ('Mercy Braime', '1939-08-06', 'North Carolina', 'Female');
insert into student (name, birthdate, address, gender) values ('Tammara Franek', '1984-02-18', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Ediva Henrichsen', '1937-08-14', 'Delaware', 'Female');
insert into student (name, birthdate, address, gender) values ('Umeko Rous', '1939-08-02', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Asa Gauvain', '2001-11-10', 'Arizona', 'Male');
insert into student (name, birthdate, address, gender) values ('Vanessa Joiris', '1969-08-16', 'Hawaii', 'Female');
insert into student (name, birthdate, address, gender) values ('Eben Hum', '1950-02-14', 'Texas', 'Male');
insert into student (name, birthdate, address, gender) values ('Brennen Portam', '1982-07-24', 'Colorado', 'Male');
insert into student (name, birthdate, address, gender) values ('Sharona Vynall', '1965-11-19', 'New York', 'Female');
insert into student (name, birthdate, address, gender) values ('Whitby Dorwood', '1961-08-15', 'California', 'Male');
insert into student (name, birthdate, address, gender) values ('Falito Matus', '1948-06-07', 'Georgia', 'Male');
insert into student (name, birthdate, address, gender) values ('Susette Moyse', '1999-10-28', 'Texas', 'Female');
insert into student (name, birthdate, address, gender) values ('Garold Kubacki', '1964-07-16', 'California', 'Male');
insert into student (name, birthdate, address, gender) values ('Stefano Tebbit', '1988-11-22', 'Florida', 'Male');
insert into student (name, birthdate, address, gender) values ('Quincey Feek', '1952-05-22', 'California', 'Male');
insert into student (name, birthdate, address, gender) values ('Boonie Windrass', '1984-04-22', 'Maryland', 'Male');
insert into student (name, birthdate, address, gender) values ('Finn Segrott', '1961-09-29', 'Connecticut', 'Male');
insert into student (name, birthdate, address, gender) values ('Alvan Jessep', '1997-01-13', 'Pennsylvania', 'Male');
insert into student (name, birthdate, address, gender) values ('Ossie Tellesson', '1933-11-28', 'Louisiana', 'Male');
insert into student (name, birthdate, address, gender) values ('Demetra Peter', '1979-01-12', 'Alaska', 'Female');
insert into student (name, birthdate, address, gender) values ('Luce Eddisforth', '1976-05-27', 'Wisconsin', 'Male');
insert into student (name, birthdate, address, gender) values ('Don Whale', '1969-12-29', 'Georgia', 'Male');

insert into course(coursename, coursecode, creditscore) values ('Math','M101','8');
insert into course(coursename, coursecode, creditscore) values ('Physics','P101','4');
insert into course(coursename, coursecode, creditscore) values ('Statistics','S101','6');
insert into course(coursename, coursecode, creditscore) values ('Algorithms','A202','7');

-- insert into instructor (name, address, phonenumber, fixedsalary) values ('Anthiathia Barritt', 'Florida', '555 888 4444', '9000');
-- insert into instructor (name, address, phonenumber, hourlysalary) values ('Ashlie Beran', 'Washington', '222 555 4444', '200');
-- insert into instructor (name, address, phonenumber, fixedsalary) values ('Phaedra Verdun', 'Texas', '777 555 7896', '7500');